export const agentEstate = [
	{
		id: 1,
		agentId: "1",
		image: "1",
		price: "1000000",
		description: "An Architectural Masterpiece in Nature's Finest Setting Green Gables is truly an extraordinary estate. The combination of man's and nature's best are brilliantly on display throughout this 74-acre Woodside, California, property which has remained intact since its inception in 1911. The creation of Mortimer Fleishhacker, banker and founder of Anglo California Bank and the Great Western Power Company, at the heart of Green Gables rests its magnificent main residence and gardens that remain home to this day for the Fleishhacker family.",
		address: "Woodside, California, 94062 United States",
		lat: 42.42994,
		lng: -78.25386,
		label: "Green Gables",
		status: "Buy"
	},
	{
		id: 2,
		agentId: "2",
		image: "2",
		price: "1200000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Lilly Rd, Belmont, NY 14813, United States",
		lat: 42.279250,
		lng: -78.013763,
		label: "Stonewall Farm",
		status: "Buy"
	},
	{
		id: 3,
		agentId: "3",
		image: "3",
		price: "1500000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Paris, NY, United States",
		lat: 42.990496,
		lng: -75.223236,
		label: "Paris",
		status: "Buy"
	},
	{
		id: 4,
		agentId: "4",
		image: "4",
		price: "1000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Plimut, NY, United States",
		lat: 42.635889,
		lng: -75.651702,
		label: "Plimut",
		status: "Buy"
	},
	{
		id: 5,
		agentId: "5",
		image: "5",
		price: "1600000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Ockham, Massachusetts, United States",
		lat: 42.352364,
		lng: -72.081146,
		label: "Ockham",
		status: "Buy"
	},
	{
		id: 6,
		agentId: "6",
		image: "6",
		price: "2000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "50 New England Ave, Summit, NJ 07901, United States",
		lat: 40.715945,
		lng: -74.366302,
		label: "50 New England Ave",
		status: "Buy"
	},
	{
		id: 7,
		agentId: "7",
		image: "7",
		price: "2200000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "71 New England Ave Summit, NJ 07901, United States",
		lat: 40.718092,
		lng: -74.367514,
		label: "71 New England Ave Summit",
		status: "Buy"
	},
	{
		id: 8,
		agentId: "8",
		image: "8",
		price: "2300000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Glen Hazel, Pittsburgh, PA, United States",
		lat: 40.407129,
		lng: -79.925384,
		label: "Glen Hazel",
		status: "Buy"
	},
	{
		id: 9,
		agentId: "9",
		image: "9",
		price: "1300000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Pennsoken Township, New Jersey, United States",
		lat: 39.970712,
		lng: -75.069427,
		label: "Pennsoken Township",
		status: "Buy"
	},
	{
		id: 10,
		agentId: "10",
		image: "10",
		price: "1500000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "98-2 Surrey St, Cambridge, MA 02138, United States",
		lat: 42.368601,
		lng: -71.114349,
		label: "98-2 Surrey St, Cambridge",
		status: "Buy"
	},
	{
		id: 11,
		agentId: "1",
		image: "11",
		price: "1000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "4300-4319 37th Rd N, Arlington, VA 22207, United States",
		lat: 38.918723,
		lng: -77.123870,
		label: "Arlington",
		status: "Rent"
	},
	{
		id: 12,
		agentId: "2",
		image: "12",
		price: "1200000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "2365 E 57th St, Cleveland, OH 44104, United States",
		lat: 41.494086,
		lng: -81.650238,
		label: "Cleveland",
		status: "Rent"
	},
	{
		id: 13,
		agentId: "3",
		image: "13",
		price: "1400000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "1400-1480 Evans Pl, Scranton, PA 18504, United States",
		lat: 41.403504,
		lng: -75.695648,
		label: "Scranton",
		status: "Rent"
	},
	{
		id: 14,
		agentId: "4",
		image: "14",
		price: "1600000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "42-80 Caldwell Dr, Ithaca, NY 14850, United States",
		lat: 42.449718,
		lng: -76.464691,
		label: "Ithaca",
		status: "Rent"
	},
	{
		id: 15,
		agentId: "5",
		image: "15",
		price: "2000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "1-129 Granby St, Manchester, NH 03102, United States",
		lat: 42.982459,
		lng: -71.487884,
		label: "Manchester",
		status: "Rent"
	},
	{
		id: 16,
		agentId: "6",
		image: "16",
		price: "1800000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "957-1023 Brentwood Rd NE, Washington, DC 20018, United States",
		lat: 38.918723,
		lng: -76.992034,
		label: "Brentwood",
		status: "Rent"
	},
	{
		id: 17,
		agentId: "7",
		image: "17",
		price: "1600000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Virginia, United States",
		lat: 37.529235,
		lng: -77.387542,
		label: "Virginia",
		status: "Rent"
	},
	{
		id: 18,
		agentId: "8",
		image: "18",
		price: "1400000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Physical Education Ct, Albany, NY 12203, United States",
		lat: 42.684364,
		lng: -73.827972,
		label: "Physical Education",
		status: "Rent"
	},
	{
		id: 19,
		agentId: "9",
		image: "19",
		price: "2400000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "100 St Barthelemy Rd, DuBois, PA 15801, United States",
		lat: 41.139272,
		lng: -78.716888,
		label: "Barthelemy",
		status: "Rent"
	},
	{
		id: 20,
		agentId: "10",
		image: "20",
		price: "1400000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Pamelia, New York, United States",
		lat: 43.995011,
		lng: -75.882136,
		label: "Pamelia",
		status: "Rent"
	},
	{
		id: 21,
		agentId: "1",
		image: "21",
		price: "1700000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "North Camden, Camden, NJ 08102, United States",
		lat: 39.945448,
		lng: -75.113372,
		label: "North Camden",
		status: "Sell"
	},
	{
		id: 22,
		agentId: "2",
		image: "22",
		price: "1400000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Maine Township, Pennsylvania, United States",
		lat: 41.006756,
		lng: -76.354827,
		label: "Maine Township",
		status: "Sell"
	},
	{
		id: 23,
		agentId: "3",
		image: "23",
		price: "1500000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Ellicott, New York, United States",
		lat: 42.124620,
		lng: -79.277191,
		label: "Ellicott",
		status: "Sell"
	},
	{
		id: 24,
		agentId: "4",
		image: "24",
		price: "1500000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Koch Rd, Milford, PA 18337, United States",
		lat: 41.337546,
		lng: -74.816741,
		label: "Milford",
		status: "Sell"
	},
	{
		id: 25,
		agentId: "5",
		image: "25",
		price: "1800000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Upper Socon Township, Pennsylvania, United States",
		lat: 40.490733,
		lng: -75.410003,
		label: "Upper Socon Township",
		status: "Sell"
	},
	{
		id: 26,
		agentId: "6",
		image: "26",
		price: "1300000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Hopwell Township, Pennsylvania, United States",
		lat: 40.232225,
		lng: -80.338085,
		label: "Hopwell Township",
		status: "Sell"
	},
	{
		id: 27,
		agentId: "7",
		image: "27",
		price: "2000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Edgevale Dr, Erie, PA 16509, United States",
		lat: 42.082801,
		lng: -80.074413,
		label: "Edgevale",
		status: "Sell"
	},
	{
		id: 28,
		agentId: "8",
		image: "28",
		price: "2000000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Newfan, New York, United States",
		lat: 43.226061,
		lng: -78.668163,
		label: "Newfan",
		status: "Sell"
	},
	{
		id: 29,
		agentId: "9",
		image: "29",
		price: "2100000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Haldimand, Ontario, Canada",
		lat: 42.937190,
		lng: -79.964550,
		label: "Haldimand",
		status: "Sell"
	},
	{
		id: 30,
		agentId: "10",
		image: "30",
		price: "1900000",
		description: "This magnificent equestrian estate is a true Thoroughbred: Four decades in the making, the property is set amid winding roads, apple orchards, rolling hills, ancient stone walls, woodlands, and ponds, with sweeping vistas of the Westchester countryside—all just an hour from New York City.",
		address: "Linton Rd, Andover, OH 44003, United States",
		lat: 41.571143,
		lng: -80.667675,
		label: "Linton",
		status: "Sell"
	}
];
